name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          echo 'This is a dispatch'
